### ISSUE TITLE
Design the boot/load sequence and components (MVP)

### ISSUE THREAD

**Issue by Sly1024** [morganstanley/ComposeUI#19]
This is a design task that might be broken up into multiple smaller pieces.

Requirements:
- ConfigLoader
  - The config is loaded by a ConfigLoader (interface)
  - The default is a JsonConfigLoader
- ModuleLoader
  - Modules are loaded by a ModuleLoader (interface)
  - We provide ModuleLoaders for .NET assemblies and web apps (URL)
- Need an executable that can be run without compiling .NET code
  - The Bootstrapper (another name?) invokes the default (JSON) config loader and 
  - Loads the modules specified in the config
- MVP (Minimum Viable Product) 
  - an `.exe` file that can load a config from a `.json` file
  - Need a JSON schema for the minimum config we need to start the app
- Communication (MessageRouter)
  - The Bootstrapper loads the default MessageRouter if no other communication module is specified

Steps to implement:
- [ ] design the JSON schema for the config
- [ ] design the ConfigLoader interface
- [ ] design the ModuleLoader interface

**Comment by BalassaMarton** [comment]
Do we want to allow 3rd party modules to load and expose custom configuration sources? 
Can we just use [Microsoft.Extensions.Configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0) for loading config? It's robust and battle-tested.
Also see the upcoming additions in .NET 6: https://andrewlock.net/exploring-dotnet-6-part-1-looking-inside-configurationmanager-in-dotnet-6/
Even if we allow custom config loaders, we should leverage the existing ecosystem in .NET.

**Comment by Sly1024** [comment]
While thinking about the schema for the config, I realized that if we have multiple module loader types, we need some kind-of registry to store/lookup the loader for a specific module.

Example:
We have a .NET module (dll) and a web module. The .NET module has a path to the .dll file, while the web module is defined by a URL that we need to load into an embedded browser.

```
{
   modules: [
      {
         type: "webModule",
         url: "https://github.com"
      },
      {
         type: "dotnetModule",
         path: "./MyModule.dll"
      }
   ]
}
```

I'm not sure yet if the "type" name is appropriate, we might call it "key" or "loader", but that value would be a key in a registry where we register all the module loaders that are available (or they register themselves when loaded).

We can add extra properties to the module specifications, that would be passed to the loader entirely. 

Also an ID could be added here to be able to refer to a specific module. I'm thinking that the same "module" (binary or web) could be loaded multiple times, but with different configurations, so we need the identifiers in the config instead of embedding them in the actual modules.

**Comment by psmulovics** [comment]
> Do we want to allow 3rd party modules to load and expose custom configuration sources? Can we just use [Microsoft.Extensions.Configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0) for loading config? It's robust and battle-tested. Also see the upcoming additions in .NET 6: https://andrewlock.net/exploring-dotnet-6-part-1-looking-inside-configurationmanager-in-dotnet-6/ Even if we allow custom config loaders, we should leverage the existing ecosystem in .NET.

Definitely we want to be able to provide custom config sources - they can read database, call a webservice, etc. We can even provide some of these providers ourselves.

**Comment by psmulovics** [comment]
> Also an ID could be added here to be able to refer to a specific module. I'm thinking that the same "module" (binary or web) could be loaded multiple times, but with different configurations, so we need the identifiers in the config instead of embedding them in the actual modules.

Definitely you need the ID, as you want to define dependencies between them to drive load order, also to programmatically target them. Also we need to provide a way for the module to access the 'extra info' property bag that was part of its definition that was provided as part of whatever config solution it used.

**Comment by BalassaMarton** [comment]
Just to throw in one more aspect, how would the configuration API look like? Are we simply storing key-value pairs? My vote would be yes, for the sake of simplicity.

**Comment by BalassaMarton** [comment]
>Definitely we want to be able to provide custom config sources
OK, but don't forget that when you say 'custom' it means modules should be able to provide them, and so the configuration API must go through the message router. It also makes it hard to control what is loaded as configuration, and you'll have to examine every module to figure out where a config entry is coming from.

**Comment by Sly1024** [comment]
On today's meeting we talked about:
- A module can tell the core module to load another config (a new configuration source/provider)
- It can get a specific config key or a section via an API,
- and it can also subscribe to changes with a key/section (like a pub-sub)
- How do we allow **setting** the configuration via an API? Need to check how the [IConfigurationSection ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfigurationsection?view=dotnet-plat-ext-5.0) and [IConfigurationProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfigurationprovider.set?view=dotnet-plat-ext-5.0#Microsoft_Extensions_Configuration_IConfigurationProvider_Set_System_String_System_String_) allows setting a value. What if there are multiple providers for a section?
- How can we extract metadata from the config: e.g. which config provider provided a specific value?
